### ISSUE TITLE
20.08 branch isn't available

### ISSUE THREAD

**Issue by bbhtt** [flathub/org.freedesktop.Sdk.Extension.node16#27]
```
flatpak install flathub org.freedesktop.Sdk.Extension.node16//20.08
Looking for matches…
Similar refs found for ‘org.freedesktop.Sdk.Extension.node16’ in remote ‘flathub’ (user):

   1) runtime/org.freedesktop.Sdk.Extension.node10/x86_64/20.08
   2) runtime/org.freedesktop.Sdk.Extension.node12/x86_64/20.08
   3) runtime/org.freedesktop.Sdk.Extension.node14/x86_64/20.08

Which do you want to use (0 to abort)? [0-3]: 
```

Probably because the build is failing https://github.com/flathub/org.freedesktop.Sdk.Extension.node16/commit/ea66d34ce9c3760a82d4bce6069d1a2e7221f64a

**Comment by gasinvein** [comment]
Since 20.08 is to be EOL soon, I'm not sure if it's worth building node16 for 20.08. Are there any apps that need it?
Thanks for reporting this anyway.

**Comment by bbhtt** [comment]
> Are there any apps that need it?

I probably need it for one app as there is no 21.08 branch for io.atom.electron.BaseApp. If https://github.com/flathub/io.atom.electron.BaseApp/pull/9 can be merged first I won't need it.

**Comment by gasinvein** [comment]
`io.atom.electron.BaseApp` was used for very old electron; recent electron apps use `org.electronjs.Electron2.BaseApp`

**Comment by bbhtt** [comment]
> `io.atom.electron.BaseApp` was used for very old electron; recent electron apps use `org.electronjs.Electron2.BaseApp`

Hm, I probably can switch it to that to avoid this branch. I'll try. I'll let you know if the 20.08 branch is still needed. Thanks!

**Comment by bbhtt** [comment]
Closing since 22.08 is out.
